### PR TITLE
Permit method override for GET

### PR DESCRIPTION
**Pull request by hadrien**

### CODE REVIEW

**Comment by merwok** [comment]
Can I ask why this is needed?  GETs should be idempotent (and therefore cached, retried, etc.), so there is a semantic issue in allowing DELETE-over-GET and other unsafe methods.

**Comment by hadrien** [comment]
Honestly, i don't know! It does not make sense to tunnel get over post method.

**Comment by hadrien** [comment]
It is not delete over get as you mentionned @merwok, is it?

**Comment by merwok** [comment]
You’re right: (:  I would still question the usefulness (what system allows POST but not GET?), but at least it’s not dangerous.

**Pull request merged**
